#!/usr/bin/env bash
# Writes infra/docker-compose/.env with strong random values for the required
# secrets, so the Compose dev stack can start. This is the Compose counterpart to
# infra/k8s/generate-secrets.sh. The .env it writes is git-ignored and never
# committed.
#
# Run from anywhere:  bash infra/docker-compose/generate-env.sh
# Overwrite an existing .env:  bash infra/docker-compose/generate-env.sh --force
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

if [[ -f "$ENV_FILE" && "${1:-}" != "--force" ]]; then
  echo "ERROR: $ENV_FILE already exists. Pass --force to overwrite it."
  exit 1
fi

# hex is URL-safe (no @, :, /, +, =), so it drops into the Mongo URI unescaped.
gen() { openssl rand -hex 24; }

KEYCLOAK_ADMIN_PASSWORD="$(gen)"
MONGO_ROOT_PASSWORD="$(gen)"
MONGO_APP_PASSWORD="$(gen)"
DMS_KEYCLOAK_ADMIN_CLIENT_SECRET="$(gen)"
DMS_DEMO_USER_PASSWORD="$(gen)"

cat > "$ENV_FILE" <<EOF
# Generated by generate-env.sh. Local development secrets, git-ignored, do not commit.
# Regenerate on a clean stack with: bash generate-env.sh --force (then docker compose down -v)

# Non-secret identities
KEYCLOAK_ADMIN_USER=local-admin
MONGO_ROOT_USER=root
MONGO_APP_USER=dms_app

# Required secrets
KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
MONGO_APP_PASSWORD=${MONGO_APP_PASSWORD}
DMS_KEYCLOAK_ADMIN_CLIENT_SECRET=${DMS_KEYCLOAK_ADMIN_CLIENT_SECRET}
DMS_DEMO_USER_PASSWORD=${DMS_DEMO_USER_PASSWORD}
EOF

chmod 600 "$ENV_FILE"

echo "Wrote $ENV_FILE (git-ignored, mode 600)."
echo "Write these down, they are not stored anywhere else:"
echo "  Demo login (all demo users): ${DMS_DEMO_USER_PASSWORD}"
echo "  Keycloak admin (local-admin): ${KEYCLOAK_ADMIN_PASSWORD}"
echo ""
echo "Next:  docker compose down -v && docker compose up --build"
