"""Text extraction from documents, OCR only when needed.

Born-digital PDFs (exported from Word, generated by a reporting tool, ...) already
carry a real text layer, so we read it directly with ``pdfminer.six`` — fast and
exact. Scanned PDFs are just page images with no text layer; those fall back to
Tesseract OCR (Poppler rasterizes each page via ``pdf2image``). Standalone images
(PNG/JPEG) are always OCR'd.

:func:`extract_text` returns an :class:`ExtractionResult` so callers can record
*which* method was used. Heavy imports (pdfminer, pdf2image, Pillow, pytesseract)
are done lazily so callers that never touch real extraction (e.g. the failure-path
unit test) do not need those engines installed.
"""

import io
from typing import NamedTuple

METHOD_EMBEDDED = "embedded"
METHOD_OCR = "ocr"

MIN_TEXT_LAYER_CHARS = 16


class ExtractionResult(NamedTuple):
    """Extracted text plus the method used to get it (``embedded`` or ``ocr``)."""

    text: str
    method: str


class OcrError(Exception):
    """Raised when a document cannot be processed (unsupported type or engine error)."""


def extract_text(
    data: bytes,
    content_type: str | None,
    file_name: str | None,
    languages: str = "eng",
) -> ExtractionResult:
    """Extract text from raw file bytes. Raises :class:`OcrError` on any failure."""
    kind = classify(content_type, file_name)
    if kind == "pdf":
        return _extract_pdf(data, languages)
    if kind == "image":
        return ExtractionResult(_ocr_image(data, languages), METHOD_OCR)
    raise OcrError(
        f"Unsupported input for extraction (content_type={content_type!r}, file_name={file_name!r}); "
        "MVP supports PDF, PNG, and JPEG only"
    )


def classify(content_type: str | None, file_name: str | None) -> str:
    """Return 'pdf', 'image', or 'unknown' from content type / filename."""
    ct = (content_type or "").lower()
    name = (file_name or "").lower()
    if ct == "application/pdf" or name.endswith(".pdf"):
        return "pdf"
    if ct.startswith("image/") or name.endswith((".png", ".jpg", ".jpeg")):
        return "image"
    return "unknown"


def _extract_pdf(data: bytes, languages: str) -> ExtractionResult:
    """Prefer the PDF's embedded text layer; fall back to OCR for scans."""
    embedded = _pdf_text_layer(data)
    if len(embedded) >= MIN_TEXT_LAYER_CHARS:
        return ExtractionResult(embedded, METHOD_EMBEDDED)
    return ExtractionResult(_ocr_pdf(data, languages), METHOD_OCR)


def count_pdf_pages(data: bytes) -> int:
    """Return the PDF's page count, or 0 if it cannot be determined."""
    from pdfminer.pdfpage import PDFPage

    try:
        return sum(1 for _ in PDFPage.get_pages(io.BytesIO(data)))
    except Exception:
        return 0


def _pdf_text_layer(data: bytes) -> str:
    """Return the PDF's embedded text layer, or '' if it has none / can't be read.

    Born-digital PDFs return their real text here; scanned PDFs return (near-)empty
    text, signalling the OCR fallback. Any pdfminer failure is treated as 'no text
    layer' so a malformed or encrypted layer never blocks the OCR path.
    """
    from pdfminer.high_level import extract_text as pdfminer_extract_text

    try:
        return (pdfminer_extract_text(io.BytesIO(data)) or "").strip()
    except Exception:
        return ""


def _ocr_image(data: bytes, languages: str) -> str:
    from PIL import Image
    import pytesseract

    try:
        with Image.open(io.BytesIO(data)) as image:
            return pytesseract.image_to_string(image, lang=languages).strip()
    except Exception as exc:  # Pillow / Tesseract errors
        raise OcrError(f"Image OCR failed: {exc}") from exc


def _ocr_pdf(data: bytes, languages: str) -> str:
    from pdf2image import convert_from_bytes
    import pytesseract

    try:
        pages = convert_from_bytes(data)
    except Exception as exc:  # Poppler rasterization errors
        raise OcrError(f"PDF rasterization failed: {exc}") from exc

    texts = []
    try:
        for page in pages:
            texts.append(pytesseract.image_to_string(page, lang=languages).strip())
    except Exception as exc:
        raise OcrError(f"PDF OCR failed: {exc}") from exc
    finally:
        for page in pages:
            page.close()

    return "\n\n".join(text for text in texts if text).strip()
