#!/usr/bin/env bash
# Make the real Secret for the stack with random passwords. Writes
# infra/k8s/01-secrets.yaml, which is git-ignored, so these never land in the repo.
#
# Run this once per cluster. Mongo bakes the app password into the database on first
# init, so changing it later wouldn't match the existing data — hence the guard below.
#
# Run from anywhere:  bash infra/k8s/generate-secrets.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$SCRIPT_DIR/01-secrets.yaml"

if [[ -f "$OUT" && "${1:-}" != "--force" ]]; then
  echo "ERROR: $OUT already exists."
  echo "Not overwriting it — that would break the existing MongoDB data, since its"
  echo "app user was created with the current password."
  echo "Only pass --force on a fresh cluster, and delete the Mongo volume too:"
  echo "  kubectl -n dms delete pvc data-mongodb-0"
  exit 1
fi

# hex is URL-safe (no /, +, =, @, :), so it drops into the Mongo URI without escaping.
gen() { openssl rand -hex 24; }

MONGO_ROOT_PW="$(gen)"
MONGO_APP_PW="$(gen)"
KC_ADMIN_PW="$(gen)"

cat > "$OUT" <<EOF
# Generated by generate-secrets.sh. Real credentials — do not commit (git-ignored).
apiVersion: v1
kind: Secret
metadata:
  name: dms-secrets
  namespace: dms
type: Opaque
stringData:
  mongo-root-username: "root"
  mongo-root-password: "${MONGO_ROOT_PW}"
  mongo-app-username: "dms_app"
  mongo-app-password: "${MONGO_APP_PW}"
  keycloak-admin-username: "admin"
  keycloak-admin-password: "${KC_ADMIN_PW}"
EOF

chmod 600 "$OUT"

echo "Wrote $OUT (git-ignored, mode 600)."
echo "Write these down now — they aren't stored anywhere else:"
echo "  Keycloak admin : admin / ${KC_ADMIN_PW}"
echo "  Mongo root pw  : ${MONGO_ROOT_PW}"
echo "  Mongo app pw   : ${MONGO_APP_PW}"
